- name: docker
  modules:
  - 00-basics
  - 01-images
  - 02-containers
  - 03-volumes
  - 04-networks
  - 05-compose
  - 06-limits
  - 07-extra

- name: kubernetes
  modules:
  # - 00-basics 
  # - 01-cluster
  # - 02-pods
  # - 03-deployments
  # - 04-services
  # - 05-ingress
  # - 06-volumes
  # - 07-configmaps-and-secrets
  - check-02
