version: "2.3"

services:
  docker-host:
    image: sbeliakou/lab-docker:latest
    container_name: docker-host
    hostname: docker-host
    volumes:
      - docker_root:/var/lib/docker
      - ../trainings.yaml:/var/_data/trainings.yaml
    tmpfs:
      - /run
      - /tmp
    ports:
      - 8022:8022
      - 8081:8081
      - 9090:9090
      - 10080-10100:10080-10100
      - 32768-32800:32768-32800
    environment:
      TRAINING: "docker"
      ANALYTICS: ecsc00a05b03.epam.com
      PROFILE: LAB2019T3A
    labels:
      project: ${PWD}
      training: docker
      lab: yes
    cpu_count: 1
    privileged: true
    network_mode: bridge

volumes:
  docker_root:
    name: docker_root
