version: "2.3"

services:
  docker-host:
    image: sbeliakou/lab-docker:latest
    container_name: docker-host
    hostname: docker-host
    volumes:
      - var_lib_docker:/var/lib/docker
    tmpfs:
      - /run
      - /tmp
    ports:
      - 8022:8022
      - 9090:9090
      - 8081:8081
      - 10080-10100:10080-10100
    env_file:
      - ~/.student
    environment:
      TRAINING: "docker"
      MODULE: "10-exam1"
      ANALYTICS: ecsc00a05b03.epam.com
      container: docker
    labels:
      project: ${PWD}
      name: docker/10-exam1
      module: 10-exam1
      training: docker
      lab: yes
    cpu_count: 1
    privileged: true
    network_mode: bridge

volumes:
  var_lib_docker:
