# version: '3.7'
# services:
#     nginx:
#         container_name: nginx
#         image: nginx:alpine
#         depends_on:
#             - tomcat
#         ports:
#             - 10084:80
#         networks:
#             - custom
#     tomcat:
#         container_name: tomcat
#         image: tomcat:jdk8-openjdk-slim
# #        ports:
#  #           - target: 80
# #              published: 8080
# #              protocol: tcp
# #              mode: ingress
#         networks:
#             - custom
# networks:
#     custom:
#         driver: bridge

version: '3.7'
services:
    nginx:
        container_name: nginx
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - 10084:80
        volumes:
            - ./default.conf:/etc/nginx/conf.d/default.conf
       # run: echo 'server{listen 80;\n server_name  localhost;\n location / {proxy_set_header   X-Forwarded-For $remote_addr;\n proxy_set_header Host $http_host;\n proxy_pass "http://127.0.0.1:8080";}}'>/etc/nginx/conf.d/default.conf
    tomcat:
        container_name: tomcat
        image: tomcat:jdk8-openjdk-slim
        #ports:
         #   - 8080:8080
#          upstream tomcat

# server {
#     listen       80;
#     server_name  localhost;
#     location / {
#         proxy_set_header   X-Forwarded-For $remote_addr;
#         proxy_set_header   Host $http_host;
#         proxy_pass  tomcat;
#     }
# }